package com.basefinder.scanner;

import net.minecraft.client.Minecraft;
import net.minecraft.core.BlockPos;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.chunk.LevelChunk;

/**
 * Analyzes chunks to determine their generation version based on block composition.
 *
 * On 2b2t (which upgraded from 1.12 to 1.19), chunks generated in different
 * Minecraft versions contain different blocks:
 *
 * - Pre-1.13: No coral, seagrass, kelp, different cave gen
 * - Pre-1.16: No ancient debris, basalt, blackstone, soul soil (Nether)
 * - Pre-1.17: No copper ore, amethyst, dripstone, tuff, deepslate below Y=0
 * - Pre-1.18: Bedrock at Y=0-4 replaced with deepslate, no terrain below Y=0
 *
 * The deepslate transition at Y=0 is the most reliable overworld indicator:
 * - New chunks (1.18+): Stone at Y=0, deepslate starts at Y=-1 and below
 * - Old chunks (pre-1.18, upgraded): Deepslate at Y=0-4 (replaced bedrock)
 */
public class ChunkAgeAnalyzer {

    private final Minecraft mc = Minecraft.getInstance();

    public enum ChunkGeneration {
        UNKNOWN,
        PRE_1_13,    // Very old generation (no ocean update)
        PRE_1_16,    // Before nether update
        PRE_1_18,    // Before caves & cliffs (bedrock at Y=0)
        POST_1_18,   // Modern generation (terrain below Y=0)
        CURRENT      // Generated by current version
    }

    /**
     * Analyze a chunk to determine its generation version.
     */
    public ChunkGeneration analyzeChunkGeneration(LevelChunk chunk) {
        if (mc.level == null) return ChunkGeneration.UNKNOWN;

        Level level = mc.level;
        int minX = chunk.getPos().getMinBlockX();
        int minZ = chunk.getPos().getMinBlockZ();

        // Overworld detection
        if (level.dimension() == Level.OVERWORLD) {
            return analyzeOverworldChunk(level, chunk, minX, minZ);
        }

        // Nether detection
        if (level.dimension() == Level.NETHER) {
            return analyzeNetherChunk(level, chunk, minX, minZ);
        }

        // End detection
        if (level.dimension() == Level.END) {
            return analyzeEndChunk(level, chunk, minX, minZ);
        }

        return ChunkGeneration.UNKNOWN;
    }

    private ChunkGeneration analyzeOverworldChunk(Level level, LevelChunk chunk, int minX, int minZ) {
        boolean hasDeepslateAtY0to4 = false;
        boolean hasStoneAtY0 = false;
        boolean hasCopperOre = false;
        boolean hasDeepslate = false;
        boolean hasTerrainBelowY0 = false;

        // Sample 8 columns instead of all 256 for performance
        int[][] sampleColumns = {{0,0}, {4,4}, {8,8}, {12,12}, {15,0}, {0,15}, {15,15}, {7,7}};

        for (int[] col : sampleColumns) {
            int x = col[0];
            int z = col[1];

            // Check Y=0 to Y=4 for deepslate (old bedrock replacement)
            for (int y = 0; y <= 4; y++) {
                BlockState state = chunk.getBlockState(new BlockPos(minX + x, y, minZ + z));
                Block block = state.getBlock();

                if (block == Blocks.DEEPSLATE) {
                    hasDeepslateAtY0to4 = true;
                }
                if (block == Blocks.STONE && y == 0) {
                    hasStoneAtY0 = true;
                }
            }

            // Check for terrain below Y=0 (sample a few Y levels)
            for (int y = -4; y >= -60; y -= 8) {
                BlockState state = chunk.getBlockState(new BlockPos(minX + x, y, minZ + z));
                if (!state.isAir() && state.getBlock() != Blocks.BEDROCK) {
                    hasTerrainBelowY0 = true;
                    break;
                }
            }

            // Check for 1.17+ blocks in relevant Y ranges (copper: Y=-16 to Y=112, deepslate: Y=-64 to Y=0)
            for (int y = -16; y < 48; y += 4) {
                BlockState state = chunk.getBlockState(new BlockPos(minX + x, y, minZ + z));
                Block block = state.getBlock();

                if (block == Blocks.COPPER_ORE || block == Blocks.DEEPSLATE_COPPER_ORE) {
                    hasCopperOre = true;
                }
                if (block == Blocks.DEEPSLATE) {
                    hasDeepslate = true;
                }
            }
        }

        // Classification logic

        // Old chunks: deepslate at Y=0-4 (replaced bedrock) and no terrain below Y=0
        if (hasDeepslateAtY0to4 && !hasTerrainBelowY0) {
            return ChunkGeneration.PRE_1_18;
        }

        // Post-1.18: has terrain below Y=0 and copper ore
        if (hasTerrainBelowY0 && hasCopperOre) {
            return ChunkGeneration.POST_1_18;
        }

        // If stone at Y=0 and terrain below, it's current gen
        if (hasStoneAtY0 && hasTerrainBelowY0) {
            return ChunkGeneration.CURRENT;
        }

        // If we find deepslate and tuff but no copper, might be upgraded
        if (hasDeepslate && !hasCopperOre) {
            return ChunkGeneration.PRE_1_18;
        }

        return ChunkGeneration.UNKNOWN;
    }

    private ChunkGeneration analyzeNetherChunk(Level level, LevelChunk chunk, int minX, int minZ) {
        boolean hasAncientDebris = false;
        boolean hasBasalt = false;
        boolean hasBlackstone = false;
        boolean hasSoulSoil = false;
        boolean hasCrimsonStem = false;
        boolean hasWarpedStem = false;

        for (int x = 0; x < 16; x += 2) { // Sample every other block for performance
            for (int z = 0; z < 16; z += 2) {
                for (int y = 0; y < 128; y++) {
                    BlockPos pos = new BlockPos(minX + x, y, minZ + z);
                    BlockState state = chunk.getBlockState(pos);
                    Block block = state.getBlock();

                    if (block == Blocks.ANCIENT_DEBRIS) hasAncientDebris = true;
                    if (block == Blocks.BASALT || block == Blocks.POLISHED_BASALT
                            || block == Blocks.SMOOTH_BASALT) hasBasalt = true;
                    if (block == Blocks.BLACKSTONE || block == Blocks.POLISHED_BLACKSTONE
                            || block == Blocks.GILDED_BLACKSTONE) hasBlackstone = true;
                    if (block == Blocks.SOUL_SOIL) hasSoulSoil = true;
                    if (block == Blocks.CRIMSON_STEM) hasCrimsonStem = true;
                    if (block == Blocks.WARPED_STEM) hasWarpedStem = true;
                }
            }
        }

        // Pre-1.16: none of the nether update blocks
        if (!hasAncientDebris && !hasBasalt && !hasBlackstone
                && !hasSoulSoil && !hasCrimsonStem && !hasWarpedStem) {
            return ChunkGeneration.PRE_1_16;
        }

        // Post-1.16: has nether update blocks
        if (hasAncientDebris || hasBasalt || hasBlackstone || hasSoulSoil) {
            return ChunkGeneration.POST_1_18; // Post nether update
        }

        return ChunkGeneration.UNKNOWN;
    }

    private ChunkGeneration analyzeEndChunk(Level level, LevelChunk chunk, int minX, int minZ) {
        // End hasn't changed much, mainly check for chorus plants and end cities
        // which indicate the chunk has been generated in 1.9+
        return ChunkGeneration.UNKNOWN;
    }

    /**
     * Quick check: is this chunk likely pre-1.18 based on the deepslate at Y=0-4?
     * This is a fast heuristic that only checks a few blocks.
     */
    public boolean isLikelyOldChunk(LevelChunk chunk) {
        int minX = chunk.getPos().getMinBlockX();
        int minZ = chunk.getPos().getMinBlockZ();

        // Check 4 corners and center at Y=0-2
        int[][] samples = {{0, 0}, {15, 0}, {0, 15}, {15, 15}, {8, 8}};

        int deepslateCount = 0;
        for (int[] sample : samples) {
            for (int y = 0; y <= 2; y++) {
                BlockPos pos = new BlockPos(minX + sample[0], y, minZ + sample[1]);
                if (chunk.getBlockState(pos).getBlock() == Blocks.DEEPSLATE) {
                    deepslateCount++;
                }
            }
        }

        // If we find deepslate at Y=0-2 in multiple sample points, it's likely old
        return deepslateCount >= 3;
    }
}
